### ISSUE TITLE
Modal content doesn't show on Safari and Chrome on iOS

### ISSUE THREAD

**Issue by evanroyce** [alpixel/ChuckCSS#1]
`.modal-content` isn't showing on Safari and Chrome on iOS. 
Adding `position: relative;` to it seems to be fixing the problem.

**Comment by ALPIXELMaiki** [comment]
@evanroyce : Which version of Safari and Chrome iOS ?
**No problem on Chrome iOS 54.0 and Safari 10**

**Comment by evanroyce** [comment]
iOS 8.1 
Safari Version 600.1.4, Latest Version of Chrome

**Comment by ALPIXELMaiki** [comment]
Safari 600 ?? :+1: 

No problem on Chrome iOS 54.0 and Safari 10
